// CONSTANTS

import env from "./env.js";

export const DAYS_IN_SECONDS = 86400;
export const SCAN_BATCH_SIZE = 5000;
export const BATCH_PROCES_DELAY = 1 * 1000; //seconds
export const DELETE_KEY_PATTERN = "REVIEWS_BY_API_KEY*";
export const SELECTED_DB = env.client.db;
export const DAYS_THRESHOLD = 14;
export const DIRECTORY = `result/db${SELECTED_DB}/`;
export const OLD_KEYS_FILENAME_TXT = `${DIRECTORY}${SELECTED_DB}-keys-older-${DAYS_THRESHOLD}-days.txt`;
export const NO_TTL_KEYS_FILENAME_TXT = `${DIRECTORY}${SELECTED_DB}-keys-no-ttl.txt`;
export const OLD_KEYS_FILENAME_JSON = `${DIRECTORY}${SELECTED_DB}-keys-older-${DAYS_THRESHOLD}-days.json`;
export const NO_TTL_KEYS_FILENAME_JSON = `${DIRECTORY}${SELECTED_DB}-keys-no-ttl.json`;

export const CONSTANTS = {
	DAYS_IN_SECONDS,
	SCAN_BATCH_SIZE,
	SELECTED_DB,
	DAYS_THRESHOLD,
	DIRECTORY,
	OLD_KEYS_FILENAME_TXT,
	NO_TTL_KEYS_FILENAME_TXT,
	OLD_KEYS_FILENAME_JSON,
	NO_TTL_KEYS_FILENAME_JSON,
};

export const CLI_ACTIONS = {
	SCAN: "SCAN",
	FLATTEN: "FLATTEN",
	MIGRATE: "MIGRATE",
	MIGRATE_STANDALONE: "MIGRATE_STANDALONE",
	DELETE_STANDLONE: "DELETE_STANDLONE",
	DELETE_CLUSTER: "DELETE_CLUSTER",
} as const;

export type CLI_ACTION = typeof CLI_ACTIONS[keyof typeof CLI_ACTIONS];	